rm -rf /var/go/.m2/repository/org/bahmni/
rm -rf /var/go/.m2/repository/org/openmrs/module/bahmniemrapi
rm -rf /var/go/.m2/repository/org/openmrs/module/bahmnimapping
rm -rf /var/go/.m2/repository/org/openmrs/module/bedmanagement
rm -rf /var/go/.m2/repository/org/openmrs/module/bedmanagement-omod
rm -rf /var/go/.m2/repository/org/openmrs/module/bahmnicore
rm -rf /var/go/.m2/repository/org/openmrs/module/bahmnicoreui
rm -rf /var/go/.m2/repository/org/openmrs/module/emrapi
rm -rf /var/go/.m2/repository/org/openmrs/module/bacteriology
rm -rf /var/go/.m2/repository/org/openmrs/module/bacteriology-api
rm -rf /var/go/.m2/repository/org/openmrs/module/bacteriology-omod
rm -rf /var/go/.m2/repository/org/openmrs/module/rulesengine
rm -rf /var/go/.m2/repository/org/openmrs/module/rulesengine-api
rm -rf /var/go/.m2/repository/org/openmrs/module/rulesengine-omod
