# Configuration of underlying software stack which are applicable for installation/upgrade

$java_installer_file="jre-7u21-linux-x64.gz"
$jre_name="jre1.7.0_21"
$tomcat_version="8.0.12"
$openerp_installer_file="openerp-7.0-20130301-002301.tar.gz"
$mysql_connector_java_version="5.1.28"
$postgresql_jdbc_connector_jar_file="postgresql-9.2-1003.jdbc4.jar"
$python_site_packages="/usr/lib/python2.6/site-packages/"
$openerp_install_location="${python_site_packages}openerp-7.0_20130301_002301-py2.6.egg"
$openerp_atomfeed_war_file_name="openerp-atomfeed-service"
$bahmni_reports_war_file_name="bahmnireports"
$openelis_war_file_name="openelis"
$reference_data_war_file_name="reference-data-0.1"
$pacs_war_file_name="pacs-integration"